name: Build
on:
  pull_request:
  push:
    branches: [main]
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run build script
      shell: pwsh
      run: ./build.ps1
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: artifacts/packages/*.nupkg
    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: artifacts/logs/*.binlog
