name: Build
on:
  pull_request:
  push:
    branches: [main]
  workflow_call:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Run build script
      shell: pwsh
      run: ./build.ps1
    - name: Upload package
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v7
      with:
        name: packages
        path: artifacts/packages/*.nupkg
    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: build-log-${{ matrix.os }}
        path: artifacts/logs/*.binlog
